steps:

- name: 'gcr.io/cloud-builders/git'
  id: 'Clone Repository'

  script: |
    #!/usr/bin/env bash
    pip install --upgrade pip
    pip install -r pipelines/requirements.txt
    ls -la

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY