steps:

- name: 'gcr.io/cloud-builders/git'
  id: 'Clone Repository'

  run: |
    git clone https://github.com/ferneutron/mlops-gcp.git

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY